on:
  push:
    branches: [ "master", "setup-cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository data
        uses: actions/checkout@v3
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.20
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
      - name: Build
        run: |
          npm ci --omit=dev
          npm run build:ui
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
