on:
  push:
    branches: [ "master", "setup-cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Emscripten
        uses: lovasoa/setup-emscripten@v1
      - name: Run a multi-line scripta
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          ls
