on:
  push:
    branches: [ "master", "setup-cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
      - name: Run a multi-line scripta
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          ls
          npm run build:wasm
          npm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
